# Generated by Django 3.0.5 on 2020-06-30 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='like',
        ),
    ]
