# Generated by Django 3.0.5 on 2020-06-30 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0002_remove_news_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_site.User'),
        ),
    ]
