# Generated by Django 3.0.5 on 2020-06-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0003_news_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='like',
        ),
        migrations.AddField(
            model_name='news',
            name='like',
            field=models.ManyToManyField(null=True, to='blog_site.User'),
        ),
    ]
