# Generated by Django 3.0.5 on 2020-07-01 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0004_auto_20200630_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='like',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_site.User')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_site.News')),
            ],
        ),
    ]
