# Generated by Django 3.0.5 on 2020-07-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0004_auto_20200706_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='blank-profile-picture-973460_640.png', null=True, upload_to='users'),
        ),
    ]
