# Generated by Django 3.0.5 on 2020-06-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0004_auto_20200614_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='cat',
        ),
        migrations.AddField(
            model_name='news',
            name='cat',
            field=models.ManyToManyField(to='blog_site.Category'),
        ),
    ]
