# Generated by Django 3.0.5 on 2020-07-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0005_auto_20200706_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
