# Generated by Django 3.0.5 on 2020-07-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0006_auto_20200707_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
