# Generated by Django 3.0.5 on 2020-06-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0006_auto_20200617_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='news/maxresdefault.jpg', upload_to='news'),
        ),
    ]
