# Generated by Django 3.0.5 on 2020-06-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0008_auto_20200622_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='news/maxresdefault.jpg', upload_to='news'),
        ),
    ]
